---
title: "Group Reflection"
editor: 
  markdown: 
    wrap: 72
---

## Skills inventory

For each skill area, describe what your group actually used it for. If
you did not use a skill, say so and note why.

### Functions & refactoring (W2)

*What we did:*

- function for plotting sample size distributions

- function for calculating weighted averages for aggregating data

- function for calculating variance using a given confidence interval

- functions for calculating lower/upper confidence interval limit

*What worked well:*

- using the function in the code once it was written validating function
  input

*What was hard:*

- had to do some research on stack overflow on how to pass the name of a
  variable to a function (eval(sym()))

### Debugging (W3)

*What we did:*

- Look at error messages and - if code ran without errors - look at
  outputs to check plausability

*What worked well:*

- First thinking about it myself, then using google and - if nothing
  else worked - ask AI

- benefiting from sites like stack-flow and slides from the previous
  course

- simplifying the code by dividing it and using test data to see where
  the problem is

- looking at the architecture of the functions and example uses in the
  Help function in RStudio

*What was hard:*

- using methods like backtrace to see where an error was

### Version control & remotes (W4)

*What we did:*

- pulling at the start of each session

*What worked well:*

*What was hard:*

- connecting local and remote (when an SSH-key is used for another git
  repo it can not be saved in general settings again)

### Quarto websites & collaborative coding (W5)

*What we did:*

- peer-reviews, assisting each other where necessary, merging each
  others branches

- worked on separate branches named after each of us

- didn't work on main directly

*What worked well:*

- distributing tasks about equally - I feel like we both contributed
  about the same keeping an over

- barely any merge conflicts and no nasty ones communicating when a
  merge conflict happened

- keeping an overview over the branches

*What was hard:*

- keeping commits small

- time management - we both did our task *very* close to respective
  deadlines.

### R packages (W6)

*What we did:*

- use imports as to not code pre-existing functionality
- experimented with making a new package project to use roxygen2

*What worked well:*

- rather clean code
- using the help function with own function descriptions when
  experimenting with roxygen2

*What was hard:*

- we had no formal package management but since we did not use that many
  packages I feel like that is okay, also most packages were standard so
  when people pull our project most users should not experience too many
  problems
- running renv snapshot troublesome while I experimented with the extra
  package project, as I had to install the new package to snapshot, but
  it couldn't complete the installation process

### Initial data analysis & data cleaning (W7)

*What we did:*

- looking at missing values

- creating a new column for the date

*What worked well:*

- looking at the documentation and inferring why values might be missing

- filtering data irrelevant to our analysis

*What was hard:*

- getting a total overview over all indicators the data includes as it
  is very comprehensive but not structured to capture that at a quick
  glance

- getting an overview over variables without making to many decisions
  (filter out specific group? age-standardized or not?)

### Reproducibility, open data & renv (W9)

*What we did:* sharing our data and linking the source, documenting code

- write above every code chunk what we are intending to do and note
  interim results

- tried to ensure a bit computational reproducibility by putting all
  essential analyses steps and packages into the script and testing

- installed renv to ensure all the packagage versions are documented

*What worked well:* - doing all analyses in the scripts for
reproducibility (not) in consoles

*What was hard:*

- maybe the reasons behind the analysis decisions aren't fully
  transparent

- we were in a rush when doing the main analysis part, so we didn't
  create a reproducible record of decisions and deviations from the
  original plan during the process

### Analysis & inference strategies (W10)

*What we did:* Correlation and regression analyses for various groups
and models

- for research question 2: first I calculated the variance of each
  observation from the given confidence intervals and then aggregated
  the variances for each year and calculated a mean value and confidence
  interval for each year, then I checked whether the confidence interval
  overlapped as a conservative estimate

*What worked well:*

- using functions and pipes to carry out the calculations
- using Claude for parts of the analysis (as explained in the code),
  comparing different models.

*What was hard:* - Inferring which models worked best and why,
interpreting the results

- the data was only available for population chunks, never for
  individuals; as the data contains sensitive observation the reason is
  probably to ensure anonymity, but in consequence we couldn't apply the
  usual statistical techniques which require information about the
  distribution of values

- for research question 2:

  - I realized afterwards, that I simply aggregated the variances from
    different sub-population group (e.g. gender, age), to calculate an
    aggregated variance, but I didn't take into account that the
    sub-populations differ from each other therefore underestimating the
    variance

  - also I forgot the Bessel correction (the n-1 instead of just n) in
    the variance formula

### Communication & visualisation (W11)

*What we did:*

- Visualizing sample sizes

- applied ggplotly for better plot readability

- loving ggplot

*What worked well:*

- Asking AI for help on visualizations, including explanations for what
  the parameters are doing

*What was hard:*

- for one graphic I first used group_by() and summary() to quickly
  simplify the data, but the grouping interfered with the plotting, took
  a lot of tries to fix

## Key analytical decisions

Describe 2–3 decisions that had a meaningful effect on your results or
workflow.

### Decision 1: Picking a data set

*What were we deciding between?* Between our former data set
(palmer-penguins) and our current data set.

*How did we reason through it?* As we did not really have any data
cleaning to do on the prior data set and the data set was listed
explicitly as being too clean for this course, we switched. The con was
that we had already written up our project proposal and were a little
frustrated as we felt like it had not been communicated enough that we
should not choose such a data set beforehand.

*In hindsight, would we decide differently?* Not really. Cleaning the
data set was less work than we anticipated and honestly, I like the
process of writing up some easier cleaning code.

The decision would stay the same, but maybe we could document this
contemplation better.

### Decision 1: already using age-standardized values (for Leos analysis)

*What were we deciding between?* The indicator values are always given
in two variants. Values as observed ("beobachtet") or age-standardized
values and we had to pick one.

*How did we reason through it?*

The age-standardized data might not show the full correlation between
two variables. For instance social support might partially correlate
with depressive symptoms through the mediator age. (less social support
might correlate with higher age, which might correlate with higher
depressive symptoms) But in the end using the age-standardized data
seemed more reasonable, as I wanted results which indicate a more direct
effect between social support and depressive symptoms and not
distortions because of age.

*In hindsight, would we decide differently?*

The decision would stay the same, but maybe we could document this
contemplation better.

## Workflow & collaboration

*How did we divide work across group members?* In the beginning, we both
did what we had time to do. For the analyses, we each did one research
question.

*What branching or Git workflow did we actually use — and did it match
the proposal?* We both worked on seperate branches and that worked
pretty consistently (Lisa just took care of some merge conflicts on
Leo's branch). We commited to that in the proposal as well. Also, we
never merged our own work - so we sticked to our proposal there. We,
however, did not always make very incremental commits.

*What would we change about how we coordinated?* Maybe not completing
everything on the day of the deadline (typing this on the day of the
deadline)

## LLM usage

Describe up to 5 significant uses of an LLM tool during the project.

### Usage 1: Inverse-Weighted Analyses

- **Tool / model:** Claude
- **What it produced:** I had prompted it to find a way to take into
  account the variance in sample sizes between groups / times of
  measurement. It then came up with Inverse Weighted Analyses and gave
  me the codes for that.
- **What we had to correct or verify:** I added the interpretation of
  the analyses as comments in the script.

### Usage 2: (research question 1) asking about inference method

- **Tool / model: Claude Sonnet 5**
- **What it produced: I asked it whether I can use the data from
  aggregated observations for a t-test or to calculate confidence
  intervals or check for overlapping confidence intervals. It told me
  that the overlapping intervals method would be a more conservative
  test.**
- **What we had to correct or verify: I looked up what the Type-I error
  chance is for the overlapping confidence likelyhood. Knol et
  al. (2011) found a 0.0056 chance for 0.95 confidence intervals.**
  =======
